In [1]:
# Import Statements

import pandas as pd
import sys

In [2]:
# Box Folder Location containing data files

apple_folder_loc = "~/Library/CloudStorage/Box-Box/Data Science Capstone"
windows_folder_loc = "~/Box/Data Science Capstone"
linux_folder_loc = ""

folder_loc = apple_folder_loc if sys.platform.startswith("darwin") else (windows_folder_loc if sys.platform.startswith("win") else linux_folder_loc)

In [4]:
# Data Files

all_vars_data_file_name = "AllVars2NFTI19-21.xlsx"
discharge_data_file_name = "NFTI Report Additions 9-13-22.xlsx"
procedures_data_file_name = "Raw Trauma Triage Registry Data NFTI.xlsx"

In [17]:
# Last 3 years dataset

all_vars_data = pd.read_excel("{}/{}".format(folder_loc, all_vars_data_file_name))
print(all_vars_data.shape)
all_vars_data.head(10)

(5146, 212)

,MRN,LastName,DOB,Age,Sex,SexCatNum,Race,RaceCatNum,EDArrival,Mechanism,...,FinalIntwithin3,FinalNFTI,NFTILevel,FinalNFTIOver,FinalNFTIUnder,FinalNFTICorrect,CribariLevel,CribariOver,CribariUnder,CribariCorrect
0,15038,Ellis ...,2027-06-15,92.40,Female,1,White,0,2019-11-08 19:18:00,Motor Vehicle Crash,...,0,0,C,0,0,1,0,0,0.0,1.0
1,132307,Milliman ...,1937-09-21,81.69,Female,1,White,0,2019-05-30 16:59:00,Motor Vehicle Crash,...,0,1,C,0,1,0,1,0,1.0,0.0
2,134166,Romano ...,1937-11-15,81.96,Male,0,White,0,2019-11-02 15:04:00,Fall,...,0,1,C,0,1,0,0,0,0.0,1.0
3,161991,Grunert ...,1934-05-15,85.52,Male,0,White,0,2019-11-23 10:30:00,Fall,...,0,0,P,0,0,1,0,0,0.0,1.0
4,163678,Russi ...,1940-02-14,79.29,Male,0,White,0,2019-05-31 04:48:00,Motor Vehicle Crash,...,1,1,C,0,1,0,1,0,1.0,0.0
5,166382,Meisenzahl ...,1940-02-06,79.68,Male,0,White,0,2019-10-13 14:12:00,Fall,...,1,1,F,0,0,1,0,1,0.0,0.0
6,173036,Gambitta ...,1940-12-26,78.89,Male,0,White,0,2019-11-16 19:02:00,Fall,...,1,1,F,0,0,1,1,0,0.0,1.0
7,247117,Howard ...,1941-12-04,77.18,Male,0,White,0,2019-02-08 17:52:00,Fall,...,0,0,C,0,0,1,0,0,0.0,1.0
8,255120,Williams ...,1938-12-20,80.04,Female,1,White,0,2019-01-05 13:36:00,Fall,...,0,1,P,0,1,0,1,0,1.0,0.0
9,262395,Morano ...,1947-04-12,72.50,Male,0,White,0,2019-10-12 21:22:00,Fall,...,0,1,C,0,1,0,0,0,0.0,1.0

In [18]:
# Disharge dataset

discharge_data = pd.read_excel("{}/{}".format(folder_loc, discharge_data_file_name))
print(discharge_data.shape)
discharge_data.head(10)

(12521, 9)

,Arrival Date,MRN,Last Name,Age,Level Activation,ED Arrival Event,Discharge event,DC Time,Vent Days
0,2014-01-01,1953514,Hursh ...,66.95,C,2014-01-01 00:50:00,2014-01-03 17:34:00,17:34:00,0
1,2014-01-01,2640649,Abdussamad ...,26.06,C,2014-01-01 06:06:00,2014-01-04 18:33:00,18:33:00,0
2,2014-01-01,1096209,Pratt ...,69.91,C,2014-01-01 18:27:00,2014-01-06 15:30:00,15:30:00,0
3,2014-01-02,2232594,Brown ...,43.81,C,2014-01-02 00:55:00,2014-01-08 15:30:00,15:30:00,0
4,2014-01-02,508251,Hall ...,55.03,C,2014-01-02 13:10:00,2014-01-02 23:00:00,23:00:00,0
5,2014-01-02,2095892,Moll ...,15.59,C,2014-01-02 15:56:00,2014-01-06 12:19:00,12:19:00,0
6,2014-01-02,2493585,Pollard ...,40.42,P,2014-01-02 18:58:00,2014-01-14 16:42:00,16:42:00,0
7,2014-01-02,779709,Parks ...,71.29,C,2014-01-02 21:31:00,2014-01-11 15:04:00,15:04:00,0
8,2014-01-03,543324,Mackay ...,51.3,C,2014-01-03 09:24:00,2014-01-13 13:54:00,13:54:00,0
9,2014-01-04,74887,Przysinda ...,80.68,F,2014-01-04 14:18:00,2014-01-14 13:05:00,13:05:00,0

In [19]:
# Procedure dataset

procedures_data = pd.read_excel("{}/{}".format(folder_loc, procedures_data_file_name), sheet_name="Patient Data 2014-2021")
print(procedures_data.shape)
procedures_data.head(10)

(12516, 42)

,MRN,Last Name,DOB,Age,Gender,Race,ED Arrival,Mechanism,Level,PH Tx,...,DC GCS,Injuries,OR Encounters,Angiography,Chest Tube,Emergent Intubation,ICP,Craniotomy,ED Dispo = OR:\nWithin 90mins?,ED Dispo = ICU: \nLOS > 2 days?
0,4346,Hurwitz ...,2022-04-10 00:00:00,95.57,Female,White,2017-11-04 19:35:00,Motor Vehicle Crash ...,P,"Spinal Immobilization, EKG Monitor ...",...,15,"-, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -...",No,No,No,No,No,No,NaN,NaN
1,12691,Cucinotti ...,2028-01-07 00:00:00,89.96,Female,White,2017-12-24 16:29:00,Fall ...,F,"Not Applicable, EKG Monitor ...",...,13,"-, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -...",No,No,No,No,No,No,NaN,NaN
2,15038,Ellis ...,2027-06-15 00:00:00,92.4,Female,White,2019-11-08 19:18:00,Motor Vehicle Crash ...,C,EKG Monitor ...,...,15,"sternum fx, sternum fx, -, -, -, -, -, -, -, -...",No,No,No,No,No,No,NaN,NaN
3,16601,Harris ...,2028-01-17 00:00:00,87.11,Male,White,2015-02-27 10:27:00,Fall ...,C,...,...,15,"hemothorax NFS, lung contusion - unilateral NF...",No,No,No,No,No,No,NaN,No
4,16601,Harris ...,2028-01-17 00:00:00,88.11,Male,White,2016-02-28 17:53:00,Fall ...,C,"EKG Monitor, Oxygen ...",...,5,cerebrum hematoma - subdural - large; massive;...,No,No,Yes,No,No,No,NaN,Yes
5,25636,McConnell ...,2023-02-26 00:00:00,95.71,Female,White,2018-11-13 09:01:00,Fall ...,C,Spinal Immobilization ...,...,14,face skin/subcutaneous/muscle lac - minor; sup...,No,No,No,No,No,No,NaN,Yes
6,28244,Mattice ...,2029-09-19 00:00:00,87.7,Male,White,2017-05-31 17:23:00,Fall ...,C,"EKG Monitor, Not Applicable ...",...,15,"-, cervical cord contusion w paresthesia - w d...",Yes,No,No,No,No,No,No,NaN
7,48601,Dailey ...,2029-06-05 00:00:00,91.48,Female,White,2020-11-27 05:43:00,Fall ...,C,Not Applicable ...,...,15,pelvic ring fx - incomplete disruption of post...,No,Yes,No,No,No,No,NaN,Yes
8,57326,Schindler ...,2026-09-13 00:00:00,94.36,Male,White,2021-01-22 01:45:00,Fall ...,C,"IV Fluids amount unknown, Oxygen by Cannula ...",...,,LE skin/subcutaneous/muscle contusion; hematom...,No,No,No,No,No,No,NaN,No
9,57837,Vanharken ...,1931-09-06 00:00:00,84.68,Male,White,2016-05-12 17:02:00,Motor Pedestrian Crash ...,C,"Spinal Immobilization, Oxygen, EKG Monitor, IV...",...,15,"pneumothorax NFS, scapula fx - body, fx GEQ 3 ...",No,No,Yes,No,No,No,NaN,Yes