In [1]:
# Import Statements

import pandas as pd
import sys

In [2]:
# Box Folder Location containing data files

apple_folder_loc = "~/Library/CloudStorage/Box-Box/Data Science Capstone"
windows_folder_loc = "~/Box/Data Science Capstone"
linux_folder_loc = ""

folder_loc = apple_folder_loc if sys.platform.startswith("darwin") else (windows_folder_loc if sys.platform.startswith("win") else linux_folder_loc)

In [4]:
# Data Files

all_vars_data_file_name = "AllVars2NFTI19-21.xlsx"
discharge_data_file_name = "NFTI Report Additions 9-13-22.xlsx"
procedures_data_file_name = "Raw Trauma Triage Registry Data NFTI.xlsx"

In [17]:
# Last 3 years dataset

all_vars_data = pd.read_excel("{}/{}".format(folder_loc, all_vars_data_file_name))
print(all_vars_data.shape)
all_vars_data.head(10)

(5146, 212)

,MRN,LastName,DOB,Age,Sex,SexCatNum,Race,RaceCatNum,EDArrival,Mechanism,...,FinalIntwithin3,FinalNFTI,NFTILevel,FinalNFTIOver,FinalNFTIUnder,FinalNFTICorrect,CribariLevel,CribariOver,CribariUnder,CribariCorrect
0,15038,Ellis ...,2027-06-15,92.40,Female,1,White,0,2019-11-08 19:18:00,Motor Vehicle Crash,...,0,0,C,0,0,1,0,0,0.0,1.0
1,132307,Milliman ...,1937-09-21,81.69,Female,1,White,0,2019-05-30 16:59:00,Motor Vehicle Crash,...,0,1,C,0,1,0,1,0,1.0,0.0
2,134166,Romano ...,1937-11-15,81.96,Male,0,White,0,2019-11-02 15:04:00,Fall,...,0,1,C,0,1,0,0,0,0.0,1.0
3,161991,Grunert ...,1934-05-15,85.52,Male,0,White,0,2019-11-23 10:30:00,Fall,...,0,0,P,0,0,1,0,0,0.0,1.0
4,163678,Russi ...,1940-02-14,79.29,Male,0,White,0,2019-05-31 04:48:00,Motor Vehicle Crash,...,1,1,C,0,1,0,1,0,1.0,0.0
5,166382,Meisenzahl ...,1940-02-06,79.68,Male,0,White,0,2019-10-13 14:12:00,Fall,...,1,1,F,0,0,1,0,1,0.0,0.0
6,173036,Gambitta ...,1940-12-26,78.89,Male,0,White,0,2019-11-16 19:02:00,Fall,...,1,1,F,0,0,1,1,0,0.0,1.0
7,247117,Howard ...,1941-12-04,77.18,Male,0,White,0,2019-02-08 17:52:00,Fall,...,0,0,C,0,0,1,0,0,0.0,1.0
8,255120,Williams ...,1938-12-20,80.04,Female,1,White,0,2019-01-05 13:36:00,Fall,...,0,1,P,0,1,0,1,0,1.0,0.0
9,262395,Morano ...,1947-04-12,72.50,Male,0,White,0,2019-10-12 21:22:00,Fall,...,0,1,C,0,1,0,0,0,0.0,1.0